docker-compose-yaml: docker-compose.yml

project: cms-druxtjs-org

tasks:
  post-rollout:
    - run:
        name: Install Drupal via Tome sync
        command: drush tome:install -y
        service: cli

    - run:
        name: Rebuild node access
        command: drush php-eval 'node_access_rebuild();'
        service: cli

    - run:
        name: Rebuild cache
        command: drush cache:rebuild
        service: cli

environments:
  main:
    routes:
      - nginx:
        - cms.druxtjs.org
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
