_core:
  default_config_hash: CEHTCpo0zzrZOJNa9_M2R_HdYKrq3v1zlRVCf66hh7U
favicon:
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
logo:
  use_default: true
third_party_settings:
  shortcut:
    module_link: true
preset_accent_color: blue
preset_focus_color: gin
enable_darkmode: auto
classic_toolbar: vertical
high_contrast_mode: false
accent_color: ''
focus_color: ''
show_description_toggle: true
show_user_theme_settings: false
icon_default: true
icon_path: ''
icon_upload: ''
