#!/bin/bash

## Description: Install Drupal
## Usage: drupal-install
## Example: "ddev drupal-install"

composer install
drush -y tome:install
drush php-eval 'node_access_rebuild();'
drush cache:rebuild
